title: Faraz Shaikh
description: Open-Source Web Developer and 3D Graphics Artist.
baseurl: ""
url: https://farazshaikh.com
livereload: true
includes_dir: "_components"
include:
  - _pages
  - tmp
  - data
exclude:
  - "tmp/**/*"
  - .gitignore
  - Gemfile
  - Gemfile.lock
host: 0.0.0.0
sass:
  sass_dir: _sass
  style: compressed
